name: smooth_hover
description: "A Flutter package that provides smooth, physics-based hover effects and tooltips for widgets, enhancing desktop and web interactions with fluid animations."
version: 0.0.2
homepage: https://github.com/sangddn/smooth_hover
repository: https://github.com/sangddn/smooth_hover
issue_tracker: https://github.com/sangddn/smooth_hover/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_physics: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
